version: '3.3'
services:
  blist:
    restart: always
    volumes:
      - '/etc/blist:/opt/blist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: blist
    image: 'xhofe/blist-aria2:latest'